language: c
cache:
  directories:
  - "$HOME/.opam/"
  - "/usr/local/Homebrew/"
before_cache:
  - opam remove --yes $PACKAGE; opam pin remove --yes $PACKAGE
  - opam clean
  - git -C /usr/local/Homebrew/ clean -xf
os:
  - linux
  - osx
env:
  global:
  - PACKAGE=nice_parser
  - OPAMYES=1
  - OPAMSKIPUPDATE=1
  - secure: LczTi6rlTEHUKmiGRB+3BUrE8HkOqI4o9lDBuiXXyiIzal6rbDAPmHIgP2HHzW0GIErAwvEhmu/yeXAY2KTxY3nRNaeI391ovGFEJX03Gwg1UI2uKCgHkWF22e6QL+GXQ72vLTaWKqyDY9H1qGWP82K1G51q3/kvR3sXT7r/qAvegNfyTiXrw+2hUe42rxyTbo1rbFe4tKmMgO/07XNur+nNArcV6mp93I23+wmcvyGnO8E7Mh6J418tk/r6hXI0GP0g1eXanzQoBxIsfdlAsWgPidEbL4QdRtGY2sEzcvHzBEqU+2pCJ7rqeheyX22y/p2JlYboL0SZOWxw1dM19HLCZDR2MzsYMzvvaRRHooOwi7vroutTqCa8Z0u6UMbpAV3HO3VGswDnna3ZDlGzSi9VSgMKEDfBNDJFhgoDUnnOiI/FG18CcxL5hD33/FZyL6Y+ExjCDXRBPbvqpGE5y74eogopZPqmPMs0Z2eZyQAGTdhnfwEbm7/iF//8lDXNiUW5zovHjubRJgBRGzu/DRVBfQcxik0nHbVpiaPy996xpnkDcJEK8Q0CVSHYsoeF3AAyuyMZrCag2UEom4Flsnil4m+DivNuQP3v6Ny7VcT0njS9GB0PDewEfkDba7Op7ADCDXj+JhApoYIM6/5Pio7ZfBWkb5vb8hStOs8sqg4=
  matrix:
  - OCAML=4.06.1
  - OCAML=4.07.1
  - OCAML=4.08.0
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
addons:
  homebrew:
    packages: opam
    update: true
  apt:
    packages: opam
    sources:
    - sourceline: 'ppa:avsm/ppa'
script:
- bash -exuv ci/travis.test.sh
- bash -exuv ci/travis.docgen.sh
